### ISSUE TITLE
Segmentation fault and problem with mlt

### ISSUE THREAD

**Issue by paulcarroty** [UnitedRPMs/kdenlive#1]
Tested on Fedora 24 LiveCD:

```
couldn't create slave: "Cannot talk to klauncher: The name org.kde.klauncher5 was not provided by any .service files"
"Could not start process Cannot talk to klauncher: The name org.kde.klauncher5 was not provided by any .service files."
doesn't know ""
Segmentation fault (core dumped)
```

![screenshot from 2016-05-18 11-06-08](https://cloud.githubusercontent.com/assets/1550705/15367263/f1403cca-1d30-11e6-997e-6683f8e667eb.png)

`/usr/share/mlt/profiles` is empty. @sergiomb2, maybe your update was too early?

**Comment by sergiomb2** [comment]
please try : 
`dnf install "kf5-kinit(x86-64)"`

**Comment by sergiomb2** [comment]
mlt problem is fixed , the rest is duplicated with  https://github.com/UnitedRPMs/packages/issues/34
